from django.urls import path

from main.views.defects import (
    CreateDefect,
    DefectsPage,
    EditDefect,
    delete_defect,
    filter_defects,
    get_defect,
)
from main.views.documents import (
    AddDocumentResult,
    CreateBatch,
    CreateDoc,
    DeleteDoc,
    DeleteDocumentRequest,
    DeleteDocumentResult,
    DocsPage,
    EditDocument,
    FilterDocs,
    GetBatches,
    GetDocument,
)
from main.views.materials import (
    AllMaterials,
    CreateMaterial,
    DeleteMaterial,
    EditMaterial,
    FilterMaterials,
    GetMaterial,
    MaterialsPage,
)
from main.views.overuses import (
    CreateOver,
    OverusesPage,
    delete_over,
    edit_over,
    filter_overs,
    get_over,
)
from main.views.pages import GetFile, Index
from main.views.products import (
    CreateFinishedProduct,
    FinishedProductsPage,
    delete_product,
    edit_product,
    filter_products,
    get_product,
)
from main.views.users import Login, logout_view
from main.views.workers import (
    CreateWorker,
    EditWorker,
    FilterWorkers,
    GetWorker,
    WorkersPage,
)

urlpatterns = [
    path("", Index.as_view()),
    path("warehouse/products/", FinishedProductsPage.as_view()),
    path("warehouse/materials/", MaterialsPage.as_view()),
    path("warehouse/overuse/", OverusesPage.as_view()),
    path("materials/add", CreateMaterial.as_view()),
    path("materials/delete/", DeleteMaterial.as_view()),
    path("materials/get/<id>", GetMaterial.as_view()),
    path("materials/all/", AllMaterials.as_view()),
    path("materials/edit/<id>", EditMaterial.as_view()),
    path("materials/filter/", FilterMaterials.as_view()),
    path("products/add/", CreateFinishedProduct.as_view()),
    path("products/delete/<id>", delete_product),
    path("products/get/<id>", get_product),
    path("products/edit/<id>/", edit_product),
    path("products/filter/", filter_products),
    path("overs/add/", CreateOver.as_view()),
    path("overs/delete/<id>", delete_over),
    path("overs/get/<id>", get_over),
    path("overs/edit/<id>/", edit_over),
    path("overs/filter/", filter_overs),
    path("ceh/workers/", WorkersPage.as_view()),
    path("ceh/workers/get/<id>", GetWorker.as_view()),
    path("ceh/workers/edit/<id>", EditWorker.as_view()),
    path("ceh/worker/add/", CreateWorker.as_view()),
    path("ceh/workers/filter/", FilterWorkers.as_view()),
    path("ceh/defects/", DefectsPage.as_view()),
    path("ceh/defects/add/", CreateDefect.as_view()),
    path("ceh/defects/filter/", filter_defects),
    path("ceh/defects/edit/<id>/", EditDefect.as_view()),
    path("ceh/defects/delete/<id>/", delete_defect),
    path("ceh/defects/get/<id>/", get_defect),
    path("docs/", DocsPage.as_view()),
    path("docs/add/", CreateDoc.as_view()),
    path("docs/<id>/add-result/", AddDocumentResult.as_view()),
    path("docs/results/delete/<id>/", DeleteDocumentResult.as_view()),
    path("docs/get/<id>/", GetDocument.as_view()),
    path("docs/edit/<id>/", EditDocument.as_view()),
    path("docs/delete/<id>/", DeleteDoc.as_view()),
    path("docs/delete-request/<id>/", DeleteDocumentRequest.as_view()),
    path("docs/filter/", FilterDocs.as_view()),
    path("login", Login.as_view()),
    path("logout", logout_view),
    path("batch/add/", CreateBatch.as_view()),
    path("batch/all/", GetBatches.as_view()),
    path("file/<path>", GetFile.as_view()),
]
