# Generated by Django 5.0 on 2025-05-09 12:42

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партия',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('features', models.CharField(max_length=255, verbose_name='Характеристики материала')),
                ('price', models.FloatField(verbose_name='Цена за единицу')),
                ('supplier', models.CharField(max_length=100, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Материалы',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('login', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=180)),
                ('role', models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Заведующий производственным цехом', 'Заведующий производственным цехом'), ('Заведующий складом', 'Заведующий складом'), ('Закройщик-конструктор', 'Закройщик-конструктор'), ('Дизайнер', 'Дизайнер'), ('Раскройщик', 'Раскройщик'), ('Упаковщик-контролёр готовой продукции', 'Упаковщик-контролёр готовой продукции'), ('Швея', 'Швея')], max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', main.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DefectiveProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество бракованных изделий')),
                ('description', models.CharField(max_length=255, verbose_name='Описание дефекта')),
                ('report', models.CharField(max_length=255, null=True, verbose_name='Ссылка на отчёт (файл/заметка)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Брак',
            },
        ),
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', ''), ('', '')], max_length=50, verbose_name='Статус заявки')),
                ('request', models.TextField(verbose_name='Текст заявки')),
                ('category', models.CharField(choices=[('закупка', ''), ('согласование', '')], max_length=50, verbose_name='Тип')),
                ('result', models.TextField(verbose_name='Результат обработки заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
            options={
                'verbose_name': 'Документооборот',
                'verbose_name_plural': 'Документооборот',
            },
        ),
        migrations.CreateModel(
            name='FinishedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название изделия')),
                ('size', models.CharField(max_length=10, verbose_name='Размер изделия')),
                ('quantity_product', models.IntegerField(verbose_name='Количество изделий в партии')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
            },
        ),
        migrations.CreateModel(
            name='OveruseOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество перерасхода')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materials')),
            ],
            options={
                'verbose_name': 'Перерасход материалов',
                'verbose_name_plural': 'Перерасход материалов',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Дата начала работы')),
                ('date_end', models.DateField(verbose_name='Дата окончания работы')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
