# Generated by Django 5.0 on 2025-05-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Партия')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('quantity_material', models.IntegerField(verbose_name='Количество на складе')),
                ('features', models.CharField(max_length=255, verbose_name='Характеристики материала')),
                ('price', models.FloatField(verbose_name='Цена за единицу')),
                ('supplier', models.CharField(max_length=100, verbose_name='Название поставщика')),
            ],
        ),
        migrations.CreateModel(
            name='DefectiveProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_defect', models.IntegerField(verbose_name='Количество бракованных изделий')),
                ('description', models.CharField(max_length=255, verbose_name='Описание дефекта')),
                ('report', models.CharField(max_length=255, verbose_name='Ссылка на отчёт (файл/заметка)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', ''), ('', '')], max_length=50, verbose_name='Статус заявки')),
                ('request', models.TextField(verbose_name='Текст заявки')),
                ('category_request', models.CharField(choices=[('закупка', ''), ('согласование', '')], max_length=50, verbose_name='Тип')),
                ('result', models.TextField(verbose_name='Результат обработки заявки')),
                ('result_upd_time', models.DateField(verbose_name='Дата и время последнего изменения')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название изделия')),
                ('size', models.CharField(max_length=10, verbose_name='Размер изделия')),
                ('quantity_product', models.IntegerField(verbose_name='Количество изделий в партии')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
            },
        ),
        migrations.CreateModel(
            name='OveruseOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_extra', models.IntegerField(verbose_name='Количество перерасхода')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materials')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('status_worker', models.CharField(choices=[('', ''), ('', '')], max_length=50, verbose_name='Должность / роль')),
                ('date_begin', models.DateField(verbose_name='Дата начала работы')),
                ('date_end', models.DateField(verbose_name='Дата окончания работы')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
            ],
        ),
    ]
