# Generated by Django 5.0 on 2025-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectiveproducts",
            name="report",
            field=models.FileField(null=True, upload_to="", verbose_name="Ссылка на отчёт (файл/заметка)"),
        ),
    ]
