# Generated by Django 5.0 on 2025-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('hash_password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Заведующий производственным цехом', 'Заведующий производственным цехом'), ('Заведующий складом', 'Заведующий складом'), ('Закройщик-конструктор', 'Закройщик-конструктор'), ('Дизайнер', 'Дизайнер'), ('Раскройщик', 'Раскройщик'), ('Упаковщик-контролёр готовой продукции', 'Упаковщик-контролёр готовой продукции'), ('Швея', 'Швея')], max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партия'},
        ),
        migrations.AlterModelOptions(
            name='defectiveproducts',
            options={'verbose_name': 'Брак', 'verbose_name_plural': 'Брак'},
        ),
        migrations.AlterModelOptions(
            name='documentmanagement',
            options={'verbose_name': 'Документооборот', 'verbose_name_plural': 'Документооборот'},
        ),
        migrations.AlterModelOptions(
            name='finishedproducts',
            options={'verbose_name': 'Готовая продукция', 'verbose_name_plural': 'Готовая продукция'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Материалы', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='overuseofmaterials',
            options={'verbose_name': 'Перерасход материалов', 'verbose_name_plural': 'Перерасход материалов'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
    ]
