# Generated by Django 5.0 on 2025-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_batch_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overuseofmaterials',
            old_name='quantity_extra',
            new_name='quantity',
        ),
    ]
