# Generated by Django 5.0 on 2025-05-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_quantity_extra_overuseofmaterials_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_begin',
            field=models.DateField(null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
