# Generated by Django 5.0 on 2025-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_documentmanagement_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.IntegerField(verbose_name='Цена за единицу'),
        ),
    ]
