# Generated by Django 5.0 on 2025-05-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_options_user_batch_user_date_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_begin',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
