# Generated by Django 5.0 on 2025-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_batch_alter_user_date_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
