# Generated by Django 5.0 on 2025-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
    ]
