# Generated by Django 5.0 on 2025-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_begin',
            field=models.TimeField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_end',
            field=models.TimeField(verbose_name='Дата окончания работы'),
        ),
    ]
