# Generated by Django 5.0 on 2025-05-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_date_begin_alter_user_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='quantity_material',
            new_name='quantity',
        ),
    ]
