# Generated by Django 5.0 on 2025-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_quantity_material_materials_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectiveproducts',
            old_name='quantity_defect',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='defectiveproducts',
            name='report',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на отчёт (файл/заметка)'),
        ),
    ]
