# Generated by Django 5.0 on 2025-05-09 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_quantity_defect_defectiveproducts_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmanagement',
            old_name='category_request',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='documentmanagement',
            name='result_upd_time',
        ),
        migrations.AddField(
            model_name='documentmanagement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
