# Generated by Django 5.0 on 2025-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_category_request_documentmanagement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_begin',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания работы'),
        ),
    ]
